"""empty message

Revision ID: 991b9f34f5bb
Revises: ad942ec5c1c8
Create Date: 2018-09-27 17:15:55.597458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '991b9f34f5bb'
down_revision = 'ad942ec5c1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('uid', sa.Integer(), nullable=True))
    op.drop_constraint('address_ibfk_1', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'user', ['uid'], ['uid'])
    op.drop_column('address', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key('address_ibfk_1', 'address', 'user', ['user_id'], ['uid'])
    op.drop_column('address', 'uid')
    # ### end Alembic commands ###
